version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.8.0
  working_directory: ~/project

jobs:
  test_regression_model_py38:
    docker:
      - image: circleci/python:3.8.0
    working_directory: ~/project/packages/regression_model
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Run tests with Python 3.8
          command: |
            sudo pip install --upgrade pip
            pip install --user tox
            tox -e py38

workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model_py38

